blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.user, name='user'),
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('level_list/', views.level_list, name='level_list'),
    path('level/<int:pk>/', views.level_detail, name='level_detail'),
    path('user', views.user, name='user'),
    path('zapros_list', views.zapros_list, name='zapros_list'),
    path('zapros/new/', views.zapros_new, name='zapros_new'),
    path('zapros/delete/<int:pk>', views.zapros_delete, name='zapros_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', include('smuggler.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django import forms
from .choices import *



class Laptop(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber + ' ' + str(self.owner)



class Printer(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber


class Shredder(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Television(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Condition(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Telephone(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Camera(models.Model):
    name = models.CharField(max_length=200, default='name')
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber



class Dispenser(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Microwave(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Display(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber

class Computer(models.Model):
    name = models.CharField(max_length=200, default='name')

    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )
    inventNumber = models.CharField(max_length=200, default='name')
    serialNumber = models.CharField(max_length=200, default='name')
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' (' + self.serialNumber + ') ' + self.inventNumber


class Document(models.Model):
    name = models.CharField(max_length=200, default='name')
    section = models.CharField(
        max_length=3,
        choices=sectionChoice,
        default='s1',
    )
    owner = models.ForeignKey('Worker', on_delete=models.CASCADE, null=True, blank=True)
    reading = models.BooleanField('Чтение', default=False)
    adding = models.BooleanField('Добавление', default=False)
    change = models.BooleanField('Изменение', default=False)
    delete = models.BooleanField('Удаление', default=False)
    lead = models.BooleanField('Проведение', default=False)
    unlead = models.BooleanField('Отмена проведения', default=False)
    watch = models.BooleanField('Просмотр', default=False)
    edit = models.BooleanField('Редактирование', default=False)
    lead_redact = models.BooleanField('Изменение проведенных', default=False)
    check_delete = models.BooleanField('Пометка на удаление', default=False)
    uncheck_delete= models.BooleanField('Снятие пометки на удаление', default=False)

    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' ' + str(self.owner)

class Worker(models.Model):
    name = models.CharField(max_length=200, default='name')
    surname = models.CharField(max_length=200, default='name')
    workerID = models.IntegerField(default=1)
    company = models.CharField(
        max_length=2,
        choices=companyChoice,
        default='pd',
    )

    job = models.CharField(
        max_length=2,
        choices=jobChoice,
        default='pd',
    )


    def publish(self):
        self.save()

    def __str__(self):
        return  self.name +' '+ self.surname

class Zapros(models.Model):
    name = models.CharField(max_length=200, default='name')
    problem = models.CharField(max_length=200, default='problem')


    def publish(self):
        self.save()

    def __str__(self):
        return self.name

class Finished(models.Model):
    name = models.CharField(max_length=200, default='name')
    problem = models.CharField(max_length=200, default='problem')


    def publish(self):
        self.save()

    def __str__(self):
        return self.name + ' ' + self.problem

blog/forms.py
from django import forms

from .models import Zapros

class PostForm(forms.ModelForm):

    class Meta:
        model = Zapros
        fields = ('name', 'problem',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

from .models import *
from .forms import PostForm

def post_list(request):
    posts = Worker.objects.order_by('job')
    blogs = Laptop.objects.filter(name='HP Pavilion').values_list('owner', flat=True)
    laptop_count = Laptop.objects.count()
    worker_count = Worker.objects.count()
    return render(request, 'blog/post_list.html', {'posts': posts, 'blogs': blogs, 'laptop_count': laptop_count, 'worker_count': worker_count })

def post_detail(request, pk):
    post = get_object_or_404(Worker, pk=pk)
    notebooks = Laptop.objects.order_by('name')
    printers = Printer.objects.order_by('name')
    shredders = Shredder.objects.order_by('name')
    televisions = Television.objects.order_by('name')
    conditions = Condition.objects.order_by('name')
    telephones = Telephone.objects.order_by('name')
    cameras = Camera.objects.order_by('name')
    dispensers = Dispenser.objects.order_by('name')
    microwaves = Microwave.objects.order_by('name')
    displays = Display.objects.order_by('name')
    computers = Computer.objects.order_by('name')
    return render(request, 'blog/post_detail.html', {'post': post, 'notebooks': notebooks, 'printers': printers, 'shredders': shredders, 'televisions': televisions, 'conditions': conditions, 'telephones': telephones, 'cameras': cameras, 'dispensers': dispensers, 'microwaves': microwaves, 'displays': displays, 'computers': computers})

def level_list(request):
    posts = Worker.objects.order_by('name')
    return render(request, 'blog/level_list.html', {'posts': posts})

def level_detail(request, pk):
    post = get_object_or_404(Worker, pk=pk)
    documents = Document.objects.order_by('id')
    return render(request, 'blog/level_detail.html', {'documents': documents, 'post': post})

def user(request):
    return render(request, 'user/user.html')

def zapros_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('zapros_list')
    else:
        form = PostForm()
    return render(request, 'user/post_edit.html', {'form': form})

def zapros_list(request):
    zaprosy = Zapros.objects.order_by('name')
    finisheds = Finished.objects.order_by('name')
    context = {
        'zaprosy': zaprosy,
        'finisheds': finisheds
    }
    return render(request, 'blog/zapros_list.html', context)

def zapros_delete(request, pk):
    current = Zapros.objects.filter(id=pk)
    current_name = current.values('name')
    current_problem = current.values('problem')
    Finished.objects.create(name = current_name, problem = current_problem)
    current.delete()
    items = Zapros.objects.all()

    context = {
        'items': items
    }
    return render(request, 'blog/zapros_list.html', context)

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/style.less' %}">
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

<script href="{% static 'js/jquery.min.js' %}"></script>
<script href="{% static 'js/code.js' %}"></script>

<script>

    function setBlock(elements){
        for(var i=0;i<elements.length;i++){
            elements[i].style.display="block";
        }
    }

    function setNone(elements){
        for(var i=0;i<elements.length;i++){
            elements[i].style.display="none";
        }
    }

    function check(){
        setNone(document.getElementsByClassName('post'));
        let input = document.getElementById('input').value.replace(/ ./g,"").replace(/\./g,'');
        document.getElementById(input).style.display = "block";
        // console.log(input);
        }
    function fullList(){
        setBlock(document.getElementsByClassName('post'));
    }

    (function() {
        let url = location.href.match('#(.*)')[1];
        document.getElementById('input').value = url;    
        check();    
    })();

    function blok_open(current){
        element = document.getElementById('content' + current);
        if(element.className.match('opened')){
            document.getElementById('content' + current).className -= 'opened';
        }
        else{
            document.getElementById('content' + current).className += 'opened';
        }
    }

</script>

blog/templates/blog/level_detail.html
{% extends 'blog/base.html' %}
    {% block content %}
    <div class="name">{{ post }}</div>
    <br>
    <div class="title">Документы</div>
    <div class="row">
        {% for document in documents %}
            {% if post == document.owner and document.get_section_display == 'Документы'%}
                <div class="blok" id="{{ document.id }}" onclick="blok_open(this.id)">
                    <div class="name">
                        {{ document.name }}
                    </div>
                    <div class="content" id="content{{document.id}}">
                        <!-- <div class="section">
                            {{ document.fileName.get_section_display }}
                        </div> -->
                        {% if document.reading %}
                            Чтение
                        {% endif %}
                        {% if document.adding %}
                            Добавление
                        {% endif %}
                        {% if document.change %}
                            Изменение
                        {% endif %}
                        {% if document.delete %}
                            Удаление
                        {% endif %}
                        {% if document.lead %}
                            Изменение
                        {% endif %}
                        {% if document.unlead %}
                            Изменение
                        {% endif %}
                        {% if document.watch %}
                            Просмотр
                        {% endif %}
                        {% if document.edit %}
                            Изменение
                        {% endif %}
                        {% if document.lead_redact %}
                            Изменение
                        {% endif %}
                        {% if document.check_delete %}
                            Изменение
                        {% endif %}
                        {% if document.uncheck_delete %}
                            Изменение
                        {% endif %}
                        {% if document.edit %}
                            Редактирование
                        {% endif %}
                        <br>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/level_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <!-- <div class="headers">
        <div>name</div>
        <div>surname</div>
    </div> -->
    {% if user.is_authenticated %}
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4"  id="{% if post.company == 'pd' %}001{% elif post.company == 'ar' %}002{% elif post.company == 'bt' %}003{% elif post.company == 'ts' %}004{% elif post.company == 'ki' %}005{% elif post.company == 'co' %}co{% else %}un{% endif %}{{ post.job }}{{ post.workerID }}">
                <a href="{% url 'level_detail' pk=post.pk %}">
                    {{ post.name }}
                    {{ post.surname }}
                    {% if post.laptop.inventNumber == '?????' %}
                        <div class="red">
                            Нет инвентарьного номера
                        </div>
                    {% endif %}
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <a href="/accounts/login/">Login</a>
    {% endif %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
    {% block content %}
        {% if user.is_authenticated %}
            {% if post %}
            <div class="list"> 
                <div class="item">
                   <div class="title">
                        Сотрудник:
                   </div>
                    {{ post.surname }} {{ post.name }}</div>
                    <div class="info">
                            {% if post.company == 'pd' %}
                                001.
                                {% elif post.company == 'ar' %}
                                    002.
                                    {% elif post.company == 'bt' %}
                                        003.
                                        {% elif post.company == 'ts' %}
                                            004.
                                            {% elif post.company == 'ki' %}
                                                005.
                                                {% elif post.company == 'co' %}
                                                    co.
                                                    {% else %}
                                                        un.
                            {% endif %}
                            {{ post.job }}.
                            {{ post.workerID }}
                    </div>
                <div class="item">
                    <div class="title">Laptops</div>
                    {% for notebook in notebooks %}
                        {% if notebook.owner == post %}
                            {{ notebook }} {{ notebook.get_company_display  }} <br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Displays</div>
                    {% for display in displays %}
                        {% if display.owner == post %}
                            {{ display }} {{ display.company }} <br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Computers</div>
                    {% for computer in computers %}
                        {% if computer.owner == post %}
                            {{ computer }} {{ computer.company }} <br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Printers</div>
                    {% for printer in printers %}
                        {% if printer.owner == post %}
                            {{ printer }} {{ printer.company }} <br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Shredder</div>
                    {% for shredder in shredders %}
                        {% if shredder.owner == post %}
                            {{ shredder }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Television</div>
                    {% for television in televisions %}
                        {% if television.owner == post %}
                            {{ television }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Condition</div>
                    {% for condition in conditions %}
                        {% if condition.owner == post %}
                            {{ condition }} {{ condition.company }} <br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Telephones</div>
                    {% for telephone in telephones %}
                        {% if telephone.owner == post %}
                            {{ telephone }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Cameras</div>
                    {% for camera in cameras %}
                        {% if camera.owner == post %}
                            {{ camera }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Dispensers</div>
                    {% for dispenser in dispensers %}
                        {% if dispenser.owner == post %}
                            {{ dispenser }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="item">
                    <div class="title">Micro Waves</div>
                    {% for microwave in microwaves %}
                        {% if microwave.owner == post %}
                            {{ microwave }}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>


            {% endif %}
        {% else %}
            <a href="/accounts/login/">Login</a>
        {% endif %}
    {% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

    <!-- <div class="headers">
        <div>name</div>
        <div>surname</div>
    </div> -->

    {% if user.is_authenticated %}

        <input type="text" id="input" >
        <button class="btn" onclick="check()">Check</button>

        <button class="btn" onclick="fullList()">Full list</button>
        <br>
        
        {% if laptop_count %}
            Total Laptops Number {{ laptop_count }}
        {% endif %}
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4 post list"  id="{% if post.company == 'pd' %}001{% elif post.company == 'ar' %}002{% elif post.company == 'bt' %}003{% elif post.company == 'ts' %}004{% elif post.company == 'ki' %}005{% elif post.company == 'co' %}co{% else %}un{% endif %}{{ post.job }}{{ post.workerID }}">
                <a href="{% url 'post_detail' pk=post.pk %}">
                    {{ post.name }}
                    {{ post.surname }}
                    <b>
                        {{ post.get_job_display }}
                    </b>
                        <div class="info">
                                {% if post.company == 'pd' %}
                                    001.
                                    {% elif post.company == 'ar' %}
                                        002.
                                        {% elif post.company == 'bt' %}
                                            003.
                                            {% elif post.company == 'ts' %}
                                                004.
                                                {% elif post.company == 'ki' %}
                                                    005.
                                                    {% elif post.company == 'co' %}
                                                        co.
                                                        {% else %}
                                                            un.
                                {% endif %}
                                {{ post.job }}.
                                {{ post.workerID }}
                        </div>
                    {% if post.laptop.inventNumber == '?????' %}
                        <div class="red">
                            Нет инвентарьного номера
                        </div>
                    {% endif %}
                </a>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <a href="/accounts/login/">Login</a>
    {% endif %}
{% endblock %}

blog/templates/blog/specific.html
{% extends 'blog/base.html' %}

{% block content %}

    <!-- <div class="headers">
        <div>name</div>
        <div>surname</div>
    </div> -->
    {% if user.is_authenticated %}
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4 post"  id="{% if post.company == 'pd' %}001.{% elif post.company == 'ar' %}002.{% elif post.company == 'bt' %}003.{% elif post.company == 'ts' %}004.{% elif post.company == 'ki' %}005.{% elif post.company == 'co' %}006.{% else %}un.{% endif %}{{ post.job }}.{{ post.workerID }}.{{ post.laptop.inventNumber }}">
                <a href="{% url 'post_detail' pk=post.pk %}">
                    {{ post.name }}
                    {{ post.surname }}
                    <b>
                        {{ post.get_job_display }}
                    </b>
                        <div>asdasasd</div>
                        <div class="info">
                                {% if post.company == 'pd' %}
                                    001.
                                    {% elif post.company == 'ar' %}
                                        002.
                                        {% elif post.company == 'bt' %}
                                            003.
                                            {% elif post.company == 'ts' %}
                                                004.
                                                {% elif post.company == 'ki' %}
                                                    005.
                                                    {% elif post.company == 'co' %}
                                                        006.
                                                        {% else %}
                                                            un.
                                {% endif %}
                                {{ post.job }}.
                                {{ post.workerID }}.
                                {{ post.laptop.inventNumber }}
                                {{ post.id }}
                        </div>
                    {% if post.laptop.inventNumber == '?????' %}
                        <div class="red">
                            Нет инвентарьного номера
                        </div>
                    {% endif %}
                </a>
            </div>
            {% endfor %}
        </div>

    <a href="/">List</a>
    {% else %}
    <a href="/accounts/login/">Login</a>
    {% endif %}
{% endblock %}

blog/templates/blog/zapros_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% for zapros in zaprosy %}
            {{ zapros }} {{ zapros.pk }} 
            <a href="{% url 'zapros_delete' zapros.pk %}" class="btn btn-warning" role="button">Delete</a>
            <br> 
        {% endfor %}
        {% for finished in finisheds %}
            {{ finished }}
        {% endfor %}
    {% endif %}
{% endblock %}